/// TradingView Charting Library style drawing toolbox registry.
///
/// This file only defines the frontend drawing-tool taxonomy and metadata.
/// It does not implement Chan theory calculations and must not be used as a
/// replacement for the Vespa chan.py-derived engine.

enum TradingViewDrawingGroup {
  cursorAndMeasure,
  lines,
  pitchforks,
  fibonacciAndGann,
  geometricShapes,
  annotation,
  patterns,
  predictionAndMeasurement,
  icons,
  chanOverlay,
}

enum TradingViewDrawingTool {
  cursor,
  crosshair,
  ruler,
  dateRange,
  priceRange,
  dateAndPriceRange,
  longPosition,
  shortPosition,
  forecast,
  barsPattern,
  ghostFeed,
  trendLine,
  infoLine,
  extendedLine,
  ray,
  horizontalLine,
  horizontalRay,
  verticalLine,
  crossLine,
  parallelChannel,
  regressionTrend,
  flatTopBottom,
  disjointChannel,
  anchoredVwap,
  anchoredText,
  pitchfork,
  schiffPitchfork,
  modifiedSchiffPitchfork,
  insidePitchfork,
  fibRetracement,
  trendBasedFibExtension,
  fibChannel,
  fibTimeZone,
  fibSpeedResistanceFan,
  fibSpeedResistanceArcs,
  fibWedge,
  pitchfan,
  gannBox,
  gannSquareFixed,
  gannSquare,
  gannFan,
  brush,
  highlighter,
  arrow,
  arrowMarker,
  rectangle,
  rotatedRectangle,
  ellipse,
  triangle,
  polyline,
  curve,
  path,
  arc,
  circle,
  text,
  anchoredNote,
  note,
  callout,
  balloon,
  priceLabel,
  priceNote,
  signpost,
  flagMark,
  abcdPattern,
  xabcdPattern,
  trianglePattern,
  threeDrivesPattern,
  headAndShoulders,
  cypherPattern,
  elliottImpulseWave,
  elliottTriangleWave,
  elliottTripleComboWave,
  elliottCorrectionWave,
  cyclicLines,
  timeCycles,
  sineLine,
  iconArrowUp,
  iconArrowDown,
  iconCheck,
  iconCross,
  iconCircle,
  iconStar,
  iconFlag,
  chanFx,
  chanFxLine,
  chanFxText,
  chanBi,
  chanBiText,
  chanSeg,
  chanSegText,
  chanZs,
  chanBiBsp,
  chanSegBsp,
  chanMergedBars,
  easyTdxIndicators,
}

class TradingViewDrawingToolMeta {
  final TradingViewDrawingTool tool;
  final TradingViewDrawingGroup group;
  final String label;
  final String description;
  final int minPoints;
  final int maxPoints;
  final bool canPersist;
  final bool requiresChanSnapshot;

  const TradingViewDrawingToolMeta({
    required this.tool,
    required this.group,
    required this.label,
    required this.description,
    required this.minPoints,
    required this.maxPoints,
    this.canPersist = true,
    this.requiresChanSnapshot = false,
  });

  bool get isSinglePoint => minPoints == 1 && maxPoints == 1;
  bool get isOpenEnded => maxPoints < 0;
}

class TradingViewDrawingToolRegistry {
  const TradingViewDrawingToolRegistry._();

  static TradingViewDrawingToolMeta _m(
    TradingViewDrawingTool tool,
    TradingViewDrawingGroup group,
    String label,
    String description,
    int minPoints,
    int maxPoints, {
    bool canPersist = true,
    bool requiresChanSnapshot = false,
  }) =>
      TradingViewDrawingToolMeta(
        tool: tool,
        group: group,
        label: label,
        description: description,
        minPoints: minPoints,
        maxPoints: maxPoints,
        canPersist: canPersist,
        requiresChanSnapshot: requiresChanSnapshot,
      );

  static final List<TradingViewDrawingToolMeta> all = [
    _m(TradingViewDrawingTool.cursor, TradingViewDrawingGroup.cursorAndMeasure, '光标', '选择、移动和编辑已绘制对象', 0, 0, canPersist: false),
    _m(TradingViewDrawingTool.crosshair, TradingViewDrawingGroup.cursorAndMeasure, '十字光标', '读取当前K线时间、价格和OHLCV', 0, 0, canPersist: false),
    _m(TradingViewDrawingTool.ruler, TradingViewDrawingGroup.cursorAndMeasure, '测量尺', '测量两点之间的涨跌幅、K线数量和价格差', 2, 2),
    _m(TradingViewDrawingTool.dateRange, TradingViewDrawingGroup.cursorAndMeasure, '日期范围', '测量横向时间/K线数量', 2, 2),
    _m(TradingViewDrawingTool.priceRange, TradingViewDrawingGroup.cursorAndMeasure, '价格范围', '测量纵向价格差和涨跌幅', 2, 2),
    _m(TradingViewDrawingTool.dateAndPriceRange, TradingViewDrawingGroup.cursorAndMeasure, '日期和价格范围', '同时测量时间跨度和价格跨度', 2, 2),
    _m(TradingViewDrawingTool.longPosition, TradingViewDrawingGroup.predictionAndMeasurement, '多头头寸', '标记入场、止损、止盈和盈亏比', 2, 3),
    _m(TradingViewDrawingTool.shortPosition, TradingViewDrawingGroup.predictionAndMeasurement, '空头头寸', '标记做空入场、止损、止盈和盈亏比', 2, 3),
    _m(TradingViewDrawingTool.forecast, TradingViewDrawingGroup.predictionAndMeasurement, '预测', '绘制主观路径推演，不参与缠论计算', 2, -1),
    _m(TradingViewDrawingTool.barsPattern, TradingViewDrawingGroup.predictionAndMeasurement, 'K线形态复制', '复制历史区间作为对照模板', 2, 2),
    _m(TradingViewDrawingTool.ghostFeed, TradingViewDrawingGroup.predictionAndMeasurement, '幽灵K线', '绘制假设性未来K线路径', 2, -1),
    _m(TradingViewDrawingTool.trendLine, TradingViewDrawingGroup.lines, '趋势线', '两点直线，最常用画线工具', 2, 2),
    _m(TradingViewDrawingTool.infoLine, TradingViewDrawingGroup.lines, '信息线', '带涨跌幅、角度等信息的趋势线', 2, 2),
    _m(TradingViewDrawingTool.extendedLine, TradingViewDrawingGroup.lines, '延长线', '两点无限延长直线', 2, 2),
    _m(TradingViewDrawingTool.ray, TradingViewDrawingGroup.lines, '射线', '从起点向右延伸的趋势线', 2, 2),
    _m(TradingViewDrawingTool.horizontalLine, TradingViewDrawingGroup.lines, '水平线', '水平价格线', 1, 1),
    _m(TradingViewDrawingTool.horizontalRay, TradingViewDrawingGroup.lines, '水平射线', '向右延伸的水平价格线', 1, 1),
    _m(TradingViewDrawingTool.verticalLine, TradingViewDrawingGroup.lines, '垂直线', '垂直时间线', 1, 1),
    _m(TradingViewDrawingTool.crossLine, TradingViewDrawingGroup.lines, '十字线', '水平和垂直交叉辅助线', 1, 1),
    _m(TradingViewDrawingTool.parallelChannel, TradingViewDrawingGroup.lines, '平行通道', '绘制价格通道', 3, 3),
    _m(TradingViewDrawingTool.regressionTrend, TradingViewDrawingGroup.lines, '回归趋势', '线性回归趋势通道', 2, 2),
    _m(TradingViewDrawingTool.flatTopBottom, TradingViewDrawingGroup.lines, '平顶/平底', '水平整理结构标注', 2, 2),
    _m(TradingViewDrawingTool.disjointChannel, TradingViewDrawingGroup.lines, '非连续通道', '分离通道结构', 4, 4),
    _m(TradingViewDrawingTool.anchoredVwap, TradingViewDrawingGroup.lines, '锚定VWAP', '从锚点开始的VWAP辅助线', 1, 1),
    _m(TradingViewDrawingTool.anchoredText, TradingViewDrawingGroup.lines, '锚定文字', '固定在图表区域的文字', 1, 1),
    _m(TradingViewDrawingTool.pitchfork, TradingViewDrawingGroup.pitchforks, '音叉线', 'Andrews Pitchfork', 3, 3),
    _m(TradingViewDrawingTool.schiffPitchfork, TradingViewDrawingGroup.pitchforks, 'Schiff 音叉', 'Schiff Pitchfork', 3, 3),
    _m(TradingViewDrawingTool.modifiedSchiffPitchfork, TradingViewDrawingGroup.pitchforks, '改良 Schiff 音叉', 'Modified Schiff Pitchfork', 3, 3),
    _m(TradingViewDrawingTool.insidePitchfork, TradingViewDrawingGroup.pitchforks, '内部音叉', 'Inside Pitchfork', 3, 3),
    _m(TradingViewDrawingTool.fibRetracement, TradingViewDrawingGroup.fibonacciAndGann, '斐波回撤', 'Fibonacci Retracement', 2, 2),
    _m(TradingViewDrawingTool.trendBasedFibExtension, TradingViewDrawingGroup.fibonacciAndGann, '趋势斐波扩展', 'Trend-based Fib Extension', 3, 3),
    _m(TradingViewDrawingTool.fibChannel, TradingViewDrawingGroup.fibonacciAndGann, '斐波通道', 'Fibonacci Channel', 3, 3),
    _m(TradingViewDrawingTool.fibTimeZone, TradingViewDrawingGroup.fibonacciAndGann, '斐波时间周期', 'Fibonacci Time Zone', 2, 2),
    _m(TradingViewDrawingTool.fibSpeedResistanceFan, TradingViewDrawingGroup.fibonacciAndGann, '斐波速度阻力扇', 'Speed Resistance Fan', 2, 2),
    _m(TradingViewDrawingTool.fibSpeedResistanceArcs, TradingViewDrawingGroup.fibonacciAndGann, '斐波速度阻力弧', 'Speed Resistance Arcs', 2, 2),
    _m(TradingViewDrawingTool.fibWedge, TradingViewDrawingGroup.fibonacciAndGann, '斐波楔形', 'Fibonacci Wedge', 3, 3),
    _m(TradingViewDrawingTool.pitchfan, TradingViewDrawingGroup.fibonacciAndGann, '角度扇形', 'Pitchfan', 2, 2),
    _m(TradingViewDrawingTool.gannBox, TradingViewDrawingGroup.fibonacciAndGann, '江恩箱', 'Gann Box', 2, 2),
    _m(TradingViewDrawingTool.gannSquareFixed, TradingViewDrawingGroup.fibonacciAndGann, '固定江恩方形', 'Fixed Gann Square', 2, 2),
    _m(TradingViewDrawingTool.gannSquare, TradingViewDrawingGroup.fibonacciAndGann, '江恩方形', 'Gann Square', 2, 2),
    _m(TradingViewDrawingTool.gannFan, TradingViewDrawingGroup.fibonacciAndGann, '江恩扇形', 'Gann Fan', 2, 2),
    _m(TradingViewDrawingTool.brush, TradingViewDrawingGroup.geometricShapes, '画笔', '自由画笔', 2, -1),
    _m(TradingViewDrawingTool.highlighter, TradingViewDrawingGroup.geometricShapes, '荧光笔', '高亮标记', 2, -1),
    _m(TradingViewDrawingTool.arrow, TradingViewDrawingGroup.geometricShapes, '箭头', '两点箭头', 2, 2),
    _m(TradingViewDrawingTool.arrowMarker, TradingViewDrawingGroup.geometricShapes, '箭头标记', '单点箭头标记', 1, 1),
    _m(TradingViewDrawingTool.rectangle, TradingViewDrawingGroup.geometricShapes, '矩形', '矩形区域标注', 2, 2),
    _m(TradingViewDrawingTool.rotatedRectangle, TradingViewDrawingGroup.geometricShapes, '旋转矩形', '旋转矩形区域', 3, 3),
    _m(TradingViewDrawingTool.ellipse, TradingViewDrawingGroup.geometricShapes, '椭圆', '椭圆区域标记', 2, 2),
    _m(TradingViewDrawingTool.triangle, TradingViewDrawingGroup.geometricShapes, '三角形', '三角形区域标记', 3, 3),
    _m(TradingViewDrawingTool.polyline, TradingViewDrawingGroup.geometricShapes, '折线', '多段折线', 2, -1),
    _m(TradingViewDrawingTool.curve, TradingViewDrawingGroup.geometricShapes, '曲线', '平滑曲线', 2, -1),
    _m(TradingViewDrawingTool.path, TradingViewDrawingGroup.geometricShapes, '路径', '多段路径', 2, -1),
    _m(TradingViewDrawingTool.arc, TradingViewDrawingGroup.geometricShapes, '圆弧', '三点圆弧', 3, 3),
    _m(TradingViewDrawingTool.circle, TradingViewDrawingGroup.geometricShapes, '圆', '圆形区域标记', 2, 2),
    _m(TradingViewDrawingTool.text, TradingViewDrawingGroup.annotation, '文本', '普通文字标注', 1, 1),
    _m(TradingViewDrawingTool.anchoredNote, TradingViewDrawingGroup.annotation, '锚定备注', '图表固定备注', 1, 1),
    _m(TradingViewDrawingTool.note, TradingViewDrawingGroup.annotation, '备注', 'K线位置备注', 1, 1),
    _m(TradingViewDrawingTool.callout, TradingViewDrawingGroup.annotation, '标注框', '带指向的说明框', 2, 2),
    _m(TradingViewDrawingTool.balloon, TradingViewDrawingGroup.annotation, '气泡', '气泡说明标注', 1, 1),
    _m(TradingViewDrawingTool.priceLabel, TradingViewDrawingGroup.annotation, '价格标签', '单点价格标签', 1, 1),
    _m(TradingViewDrawingTool.priceNote, TradingViewDrawingGroup.annotation, '价格备注', '价格位置备注', 1, 1),
    _m(TradingViewDrawingTool.signpost, TradingViewDrawingGroup.annotation, '路标', '事件路标式标注', 1, 1),
    _m(TradingViewDrawingTool.flagMark, TradingViewDrawingGroup.annotation, '旗标', '旗帜事件标记', 1, 1),
    _m(TradingViewDrawingTool.abcdPattern, TradingViewDrawingGroup.patterns, 'ABCD 形态', '四点谐波/结构形态', 4, 4),
    _m(TradingViewDrawingTool.xabcdPattern, TradingViewDrawingGroup.patterns, 'XABCD 形态', '五点谐波形态', 5, 5),
    _m(TradingViewDrawingTool.trianglePattern, TradingViewDrawingGroup.patterns, '三角形形态', '三角收敛/扩散形态', 5, 5),
    _m(TradingViewDrawingTool.threeDrivesPattern, TradingViewDrawingGroup.patterns, '三驱动形态', '三段驱动结构', 6, 6),
    _m(TradingViewDrawingTool.headAndShoulders, TradingViewDrawingGroup.patterns, '头肩形态', '头肩顶/底结构标注', 5, 5),
    _m(TradingViewDrawingTool.cypherPattern, TradingViewDrawingGroup.patterns, 'Cypher 形态', 'Cypher 谐波形态', 5, 5),
    _m(TradingViewDrawingTool.elliottImpulseWave, TradingViewDrawingGroup.patterns, '艾略特推动浪', '1-5 推动浪标注', 6, 6),
    _m(TradingViewDrawingTool.elliottTriangleWave, TradingViewDrawingGroup.patterns, '艾略特三角浪', 'ABCDE 三角调整标注', 5, 5),
    _m(TradingViewDrawingTool.elliottTripleComboWave, TradingViewDrawingGroup.patterns, '艾略特三重组合浪', '复杂组合调整标注', 7, 7),
    _m(TradingViewDrawingTool.elliottCorrectionWave, TradingViewDrawingGroup.patterns, '艾略特调整浪', 'ABC 调整浪标注', 4, 4),
    _m(TradingViewDrawingTool.cyclicLines, TradingViewDrawingGroup.patterns, '循环线', '等间距时间循环线', 2, 2),
    _m(TradingViewDrawingTool.timeCycles, TradingViewDrawingGroup.patterns, '时间循环', '周期性时间弧/线', 2, 2),
    _m(TradingViewDrawingTool.sineLine, TradingViewDrawingGroup.patterns, '正弦线', '周期波形辅助线', 2, 2),
    _m(TradingViewDrawingTool.iconArrowUp, TradingViewDrawingGroup.icons, '上箭头图标', '单点看多/向上标记', 1, 1),
    _m(TradingViewDrawingTool.iconArrowDown, TradingViewDrawingGroup.icons, '下箭头图标', '单点看空/向下标记', 1, 1),
    _m(TradingViewDrawingTool.iconCheck, TradingViewDrawingGroup.icons, '对勾图标', '确认标记', 1, 1),
    _m(TradingViewDrawingTool.iconCross, TradingViewDrawingGroup.icons, '叉号图标', '否定/无效标记', 1, 1),
    _m(TradingViewDrawingTool.iconCircle, TradingViewDrawingGroup.icons, '圆点图标', '重点位置标记', 1, 1),
    _m(TradingViewDrawingTool.iconStar, TradingViewDrawingGroup.icons, '星标图标', '重点机会标记', 1, 1),
    _m(TradingViewDrawingTool.iconFlag, TradingViewDrawingGroup.icons, '旗帜图标', '事件旗帜标记', 1, 1),
    _m(TradingViewDrawingTool.chanFx, TradingViewDrawingGroup.chanOverlay, '缠论分型', '显示 Vespa/chan.py 口径分型结果', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanFxLine, TradingViewDrawingGroup.chanOverlay, '分型连线', '显示分型连接辅助线，不参与计算', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanFxText, TradingViewDrawingGroup.chanOverlay, '分型文字', '显示分型顶/底文字', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanBi, TradingViewDrawingGroup.chanOverlay, '缠论笔', '显示 Vespa/chan.py 口径笔结果', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanBiText, TradingViewDrawingGroup.chanOverlay, '笔编号', '显示笔编号文字', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanSeg, TradingViewDrawingGroup.chanOverlay, '缠论线段', '显示 Vespa/chan.py 口径线段结果', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanSegText, TradingViewDrawingGroup.chanOverlay, '线段编号', '显示线段编号文字', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanZs, TradingViewDrawingGroup.chanOverlay, '缠论中枢', '显示 Vespa/chan.py 口径中枢结果', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanBiBsp, TradingViewDrawingGroup.chanOverlay, '笔买卖点', '显示后端返回的 level=bi BSP，不在前端重算', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanSegBsp, TradingViewDrawingGroup.chanOverlay, '线段买卖点', '显示后端返回的 level=seg BSP，不在前端重算', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.chanMergedBars, TradingViewDrawingGroup.chanOverlay, '合并K线', '显示包含关系处理后的合并K线外框', 0, 0, canPersist: false, requiresChanSnapshot: true),
    _m(TradingViewDrawingTool.easyTdxIndicators, TradingViewDrawingGroup.chanOverlay, 'easy-tdx 指标', '显示 easy-tdx OHLCV 与 easy_tdx.indicator 展示指标；不参与 chan.py 缠论结构计算', 0, 0, canPersist: false, requiresChanSnapshot: true),
  ];

  static Map<TradingViewDrawingGroup, List<TradingViewDrawingToolMeta>> byGroup() {
    final result = <TradingViewDrawingGroup, List<TradingViewDrawingToolMeta>>{};
    for (final meta in all) {
      result.putIfAbsent(meta.group, () => <TradingViewDrawingToolMeta>[]).add(meta);
    }
    return result;
  }

  static TradingViewDrawingToolMeta metaOf(TradingViewDrawingTool tool) {
    return all.firstWhere((meta) => meta.tool == tool);
  }
}
