import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../core/models/bsp.dart';
import '../../core/models/chan_snapshot.dart';
import '../../core/models/level_relation.dart';
import '../../core/models/multi_level_chan_snapshot.dart';
import '../../core/runtime/runtime_path.dart';
import '../../data/python_multi_level_chan_analysis_source.dart';
import '../widgets/origin_kline_chart.dart';

class S13SingleStockReplayPage extends StatefulWidget{const S13SingleStockReplayPage({super.key});@override State<S13SingleStockReplayPage> createState()=>_S13SingleStockReplayPageState();}
enum _S13Panel{stock,levels,replay,chart,evidence}
class _S13SingleStockReplayPageState extends State<S13SingleStockReplayPage>{
 static const _levelOptions=<String>['DAILY','MIN60','MIN30','MIN15','MIN5','MIN1'];static const _levelOptionSet=<String>{'DAILY','MIN60','MIN30','MIN15','MIN5','MIN1'};static const _stepFrameOptions=<int>[24,40,60,120,391];static final _defaultStartDate=DateTime(1990,1,1);
 final _backendUrlController=TextEditingController(text:'app-managed bundled Python'),_symbolController=TextEditingController(text:'600340'),_marketController=TextEditingController(text:'SH'),_startController=TextEditingController(),_endController=TextEditingController();
 final _selectedLevels=<String>['DAILY','MIN30','MIN5'];final _enabledEasyTdxIndicators=<String>{};
 PythonMultiLevelChanAnalysis? _analysis;_S13Panel _panel=_S13Panel.stock;String _mode='once',_activeLevel='DAILY',_status='未加载；start 空=1990-01-01，end 空=系统当前时间，count 已删除',_lastLevelValidation='级别组合待校验';bool _loading=false,_showBspCandidateTrail=true;int _maxStepFrames=60,_frameIndex=0,_windowSize=90;double _priceScale=1.0;int? _viewEndIndex,_crosshairIndex;
 @override void dispose(){_backendUrlController.dispose();_symbolController.dispose();_marketController.dispose();_startController.dispose();_endController.dispose();super.dispose();}
 DateTime get _defaultEndDate=>DateTime.now();int get _frameCount=>_analysis?.frames.length??0;bool get _isStepMode=>_mode=='step';bool get _hasStepFrames=>_isStepMode&&_frameCount>0;int get _safeFrameIndex=>_frameCount<=0?0:_frameIndex.clamp(0,_frameCount-1).toInt();String get _stepFrameLabel=>!_isStepMode?'once final snapshot':(_frameCount<=0?'step no frames':'${_safeFrameIndex+1}/$_frameCount');
 List<String> get _normalizedLevels=><String>[for(final level in _levelOptions)if(_selectedLevels.map((v)=>v.trim().toUpperCase()).contains(level))level];
 MultiLevelChanSnapshot? get _currentSnapshot{final a=_analysis;if(a==null)return null;if(_isStepMode){if(a.frames.isEmpty)return null;return a.frames[_safeFrameIndex];}return a.snapshot;}
 ChanSnapshot? get _activeSnapshot{final c=_currentSnapshot;if(c==null)return null;final level=c.snapshots.containsKey(_activeLevel)?_activeLevel:c.safeActiveLevel;return c.of(level);}
 ChanSnapshot? get _displaySnapshot{final s=_activeSnapshot;if(s==null)return null;final trail=_bspCandidateTrail(s);if(trail.isEmpty)return s;return ChanSnapshot(rawBars:s.rawBars,mergedBars:s.mergedBars,fxs:s.fxs,bis:s.bis,segs:s.segs,zss:s.zss,bsps:<BspPoint>[...trail,...s.bsps],segZss:s.segZss,eigenBoxes:s.eigenBoxes,segEigenBoxes:s.segEigenBoxes,indicators:s.indicators);}
 int get _bspCandidateTrailCount{final s=_activeSnapshot;return s==null?0:_bspCandidateTrail(s).length;}
 List<BspPoint> _bspCandidateTrail(ChanSnapshot current){final a=_analysis;if(!_showBspCandidateTrail||!_isStepMode||a==null||a.frames.isEmpty)return const <BspPoint>[];final level=_activeLevel.trim().toUpperCase();final live=current.bsps.map(_bspKey).toSet();final sure=<String>{};final trail=<String,BspPoint>{};for(var i=0;i<=_safeFrameIndex&&i<a.frames.length;i++){final s=a.frames[i].of(level);if(s==null)continue;for(final p in s.bsps){final k=_bspKey(p);if(p.confirmed){sure.add(k);trail.remove(k);}else if(!sure.contains(k)){trail[k]=_trailPoint(p);}}}for(final k in live){trail.remove(k);}return trail.values.toList(growable:false)..sort((a,b)=>a.rawIndex.compareTo(b.rawIndex));}
 String _bspKey(BspPoint p){final side=p.isSell?'sell':(p.isBuy?'buy':'bsp');return '${p.level.trim().toLowerCase()}|$side|${p.type.trim().toLowerCase()}|${p.rawIndex}|${p.biIndex??-1}|${p.segIndex??-1}|${p.zsIndex??-1}';}
 BspPoint _trailPoint(BspPoint p){final t=p.type.trim().isEmpty?'BSP':p.type.trim();return BspPoint(index:p.index,rawIndex:p.rawIndex,time:p.time,price:p.price,type:'$t候选轨迹',level:p.level,biIndex:p.biIndex,segIndex:p.segIndex,zsIndex:p.zsIndex,confirmed:false);}
 List<LevelRelation> get _visibleDownRelations{final c=_currentSnapshot;if(c==null||c.relations.isEmpty)return const <LevelRelation>[];final parent=_activeLevel.trim().toUpperCase();final ps=c.of(parent);if(ps==null||ps.rawBars.isEmpty)return const <LevelRelation>[];final parentMax=ps.rawBars.length-1;final levels=c.snapshots.keys.map((v)=>v.trim().toUpperCase()).toSet();final seen=<String>{};final links=<LevelRelation>[];final sorted=c.relations.toList(growable:false)..sort((a,b){final x=a.parentRawIndex.compareTo(b.parentRawIndex);return x!=0?x:a.childStartRawIndex.compareTo(b.childStartRawIndex);});for(final r in sorted){final rp=r.parentLevel.trim().toUpperCase(),child=r.childLevel.trim().toUpperCase();if(rp!=parent||!levels.contains(child))continue;if(r.parentRawIndex<0||r.parentRawIndex>parentMax)continue;final cs=c.of(child);if(cs==null||cs.rawBars.isEmpty)continue;final childMax=cs.rawBars.length-1;if(r.childStartRawIndex<0||r.childEndRawIndex<r.childStartRawIndex||r.childEndRawIndex>childMax)continue;final key='$rp:${r.parentRawIndex}:$child:${r.childStartRawIndex}:${r.childEndRawIndex}';if(!seen.add(key))continue;links.add(r);if(links.length>=8)break;}return links;}
 DateTime _dateOrDefault(TextEditingController c,String label,DateTime fallback){final t=c.text.trim();if(t.isEmpty)return fallback;final p=DateTime.tryParse(t.replaceAll('/','-'));if(p==null)throw FormatException('$label must be yyyy-MM-dd, current=$t');return p;}String _fmtDate(DateTime v)=>v.toIso8601String().split('T').first;String get _effectiveWindowText{try{return '${_fmtDate(_dateOrDefault(_startController,'start',_defaultStartDate))}~${_fmtDate(_dateOrDefault(_endController,'end',_defaultEndDate))}';}catch(_){return'invalid';}}
 _LevelValidationResult _validateSelectedLevels(){final raw=[for(final l in _selectedLevels)l.trim().toUpperCase()];final n=_normalizedLevels;if(raw.isEmpty)return _LevelValidationResult(false,n,'级别组合无效：至少选择两个级别');final bad=raw.where((l)=>!_levelOptionSet.contains(l)).toList(growable:false);if(bad.isNotEmpty)return _LevelValidationResult(false,n,'级别组合无效：不支持 ${bad.join(',')}');if(raw.toSet().length!=raw.length)return _LevelValidationResult(false,n,'级别组合无效：存在重复级别');if(n.length<2)return _LevelValidationResult(false,n,'级别组合无效：至少选择两个级别');if(n.length!=raw.length)return _LevelValidationResult(true,n,'级别组合已归一化：${n.join(',')}');return _LevelValidationResult(true,n,'级别组合有效：${n.join(',')}');}
 Future<void> _loadReplay()async{if(_loading)return;final lv=_validateSelectedLevels();setState(()=>_lastLevelValidation=lv.message);if(!lv.ok){_showMessage(lv.message);return;}late final DateTime startDate,endDate;try{startDate=_dateOrDefault(_startController,'start',_defaultStartDate);endDate=_dateOrDefault(_endController,'end',_defaultEndDate);}catch(e){_showMessage('$e');return;}if(startDate.isAfter(endDate)){_showMessage('时间窗口无效：开始时间不能晚于结束时间');return;}setState((){_loading=true;_status='S13 loading analyze_multi ${_mode.toUpperCase()} levels:${lv.normalizedLevels.join(',')} window:${_fmtDate(startDate)}~${_fmtDate(endDate)} runtime:${RuntimePathController.current.wireName}';});final source=PythonMultiLevelChanAnalysisSource(baseUrl:_backendUrlController.text.trim());try{final a=await source.analyzeMulti(mode:_mode,market:_marketController.text.trim().toUpperCase(),code:_symbolController.text.trim(),levels:lv.normalizedLevels,adjust:'QFQ',mainLevel:lv.normalizedLevels.first,clockLevel:lv.normalizedLevels.first,startDate:startDate,endDate:endDate,runtimePath:RuntimePathController.current,config:<String,dynamic>{'bi_algo':'normal','seg_algo':'chan','zs_algo':'normal',if(_mode=='step')'max_step_frames':_maxStepFrames});if(!mounted)return;setState((){_analysis=a;_frameIndex=0;final init=_currentSnapshot??a.snapshot;_activeLevel=init.safeActiveLevel;_viewEndIndex=null;_crosshairIndex=null;_priceScale=1.0;_status=_buildStatus(a,startDate,endDate);});_showMessage('S13 replay loaded');}catch(e){if(!mounted)return;final detail=_friendlyLoadError(e);setState(()=>_status=detail);_showMessage(detail);}finally{source.close();if(mounted)setState(()=>_loading=false);}}
 String _friendlyLoadError(Object e)=>'S13 replay load failed: $e | request: symbol=${_symbolController.text.trim()} market=${_marketController.text.trim().toUpperCase()} mode=$_mode levels=${_normalizedLevels.join(',')} window=$_effectiveWindowText runtime_path=${RuntimePathController.current.wireName}';
 void _setReplayMode(String v){if(_mode==v)return;setState((){_mode=v;_frameIndex=0;_viewEndIndex=null;_crosshairIndex=null;_priceScale=1.0;final c=_currentSnapshot;if(c!=null)_activeLevel=c.snapshots.containsKey(_activeLevel)?_activeLevel:c.safeActiveLevel;});}
 void _setFrameIndex(int index){final a=_analysis;if(a==null||a.frames.isEmpty)return;final next=index.clamp(0,a.frames.length-1).toInt();final f=a.frames[next];final level=f.snapshots.containsKey(_activeLevel)?_activeLevel:f.safeActiveLevel;setState((){_frameIndex=next;_activeLevel=level;_viewEndIndex=null;_crosshairIndex=null;_priceScale=1.0;_status='S13 step frame ${next+1}/${a.frames.length} active:$level relations:${f.relations.length} visible_links:${_visibleDownRelations.length} candidate_trail:$_bspCandidateTrailCount';});}
 void _stepFrameBy(int d)=>_setFrameIndex(_safeFrameIndex+d);void _jumpToLatestFrame()=>_setFrameIndex(_frameCount-1);
 void _jumpDownRelation(LevelRelation r){final c=_currentSnapshot;if(c==null)return;final child=r.childLevel.trim().toUpperCase();if(!c.snapshots.containsKey(child)){_showMessage('区间套子级别未加载：$child');return;}final s=c.of(child);if(s==null||s.rawBars.isEmpty){_showMessage('区间套子级别当前帧无K线：$child');return;}final max=s.rawBars.length-1;if(r.childStartRawIndex<0||r.childEndRawIndex<r.childStartRawIndex||r.childEndRawIndex>max){_showMessage('区间套尚未在当前step完整出现：$child ${r.childStartRawIndex}-${r.childEndRawIndex} / max=$max');return;}setState((){_activeLevel=child;_viewEndIndex=r.childEndRawIndex.clamp(0,max).toInt();_crosshairIndex=r.childStartRawIndex.clamp(0,max).toInt();_priceScale=1.0;_panel=_S13Panel.levels;});_showMessage('区间套跳转：${r.parentLevel}@${r.parentRawIndex} ↓ $child ${r.childStartRawIndex}-${r.childEndRawIndex} | frame=$_stepFrameLabel');}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF0D1117),body:SafeArea(child:Row(children:<Widget>[_leftToolbar(),const VerticalDivider(width:1,thickness:1,color:Color(0x223C4658)),SizedBox(width:430,child:Padding(padding:const EdgeInsets.all(10),child:_settingsPanel())),const VerticalDivider(width:1,thickness:1,color:Color(0x223C4658)),Expanded(child:Padding(padding:const EdgeInsets.all(10),child:_chartPanel(_displaySnapshot)))])));
 Widget _leftToolbar()=>Container(width:52,color:const Color(0xEE111722),padding:const EdgeInsets.symmetric(vertical:10),child:Column(children:<Widget>[_tool(Icons.settings,'股票基础设置',_S13Panel.stock),_tool(Icons.layers,'多级别设置',_S13Panel.levels),_tool(Icons.play_circle,'复盘执行',_S13Panel.replay),_tool(Icons.show_chart,'图层指标',_S13Panel.chart),_tool(Icons.article,'复盘证据',_S13Panel.evidence),const Spacer(),IconButton(tooltip:'载入复盘',onPressed:_loading?null:_loadReplay,icon:_loading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.refresh),color:const Color(0xFFFFD54F))]));
 Widget _tool(IconData icon,String tip,_S13Panel p){final selected=_panel==p;return Padding(padding:const EdgeInsets.only(bottom:8),child:IconButton(tooltip:tip,onPressed:()=>setState(()=>_panel=p),icon:Icon(icon,size:19),color:selected?Colors.black:Colors.white70,style:IconButton.styleFrom(backgroundColor:selected?const Color(0xFFFFD54F):const Color(0xFF1C2330),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12)))));}
 Widget _settingsPanel()=>switch(_panel){_S13Panel.stock=>_stockPanel(),_S13Panel.levels=>_levelsPanel(),_S13Panel.replay=>_replayPanel(),_S13Panel.chart=>_chartSettingsPanel(),_S13Panel.evidence=>_evidencePanel()};
 Widget _stockPanel()=>_panelBox('股票基础设置',SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Wrap(spacing:8,runSpacing:8,children:<Widget>[_input(_backendUrlController,'backend',width:210,enabled:false),_input(_symbolController,'symbol',width:104),_input(_marketController,'market',width:78),_input(_startController,'start 可空',width:132),_input(_endController,'end 可空',width:132)]),const SizedBox(height:10),_chip('window_policy','start 空=1990-01-01；end 空=系统当前时间；count 已删除',true),const SizedBox(height:8),_chip('effective_window',_effectiveWindowText,_effectiveWindowText!='invalid'),const SizedBox(height:8),Text(_status,maxLines:7,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:12))])));
 Widget _levelsPanel()=>_panelBox('多级别设置',SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[const Text('加载级别',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:8),Wrap(spacing:6,runSpacing:6,children:[for(final l in _levelOptions)_levelChip(l)]),const SizedBox(height:12),const Text('当前图表级别',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:8),Wrap(spacing:6,runSpacing:6,children:[for(final l in _normalizedLevels)_activeLevelChip(l)]),const SizedBox(height:10),_chip('step_frame',_stepFrameLabel,!_isStepMode||_hasStepFrames),const SizedBox(height:8),_chip('candidate_trail','$_bspCandidateTrailCount',!_isStepMode||_showBspCandidateTrail),const SizedBox(height:8),_chip('level_validation',_lastLevelValidation,_lastLevelValidation.contains('有效')||_lastLevelValidation.contains('归一化')),const SizedBox(height:8),_chip('normalized_levels',_normalizedLevels.join(','),_normalizedLevels.length>=2)])));
 Widget _replayPanel()=>_panelBox('复盘执行设置',SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Wrap(spacing:8,runSpacing:8,children:<Widget>[_modeChip('once'),_modeChip('step'),_dropdownInt('step frames',_maxStepFrames,_stepFrameOptions,(v)=>setState(()=>_maxStepFrames=v),width:132)]),const SizedBox(height:10),_stepControlPanel(),const SizedBox(height:10),FilledButton.icon(onPressed:_loading?null:_loadReplay,icon:const Icon(Icons.play_arrow,size:16),label:const Text('载入复盘')),const SizedBox(height:8),OutlinedButton.icon(onPressed:_analysis==null?null:()=>_copyText('复制复盘证据',_buildReplayEvidenceText(_analysis!)),icon:const Icon(Icons.copy,size:14),label:const Text('复制复盘证据'),style:_copyButtonStyle()),const SizedBox(height:10),_chip('runtime_path',RuntimePathController.current.wireName,RuntimePathController.current.isHighSpeed),const SizedBox(height:8),_chip('replay_mode',_mode,true),const SizedBox(height:8),_chip('chart_interval_links','${_visibleDownRelations.length}',_visibleDownRelations.isNotEmpty),const SizedBox(height:8),_chip('bsp_candidate_trail','$_bspCandidateTrailCount',_showBspCandidateTrail)])));
 Widget _stepControlPanel(){if(!_isStepMode)return _chip('temporal_view','once 模式使用最终快照；切到 step 后使用当前帧',true);final enabled=_frameCount>0;return Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Colors.white.withValues(alpha:0.05),borderRadius:BorderRadius.circular(10),border:Border.all(color:Colors.white24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Text('step 当下性：$_stepFrameLabel',style:const TextStyle(color:Colors.white70,fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:6),Row(children:<Widget>[IconButton(onPressed:enabled&&_safeFrameIndex>0?()=>_setFrameIndex(0):null,icon:const Icon(Icons.first_page),color:Colors.white70,tooltip:'第一帧'),IconButton(onPressed:enabled&&_safeFrameIndex>0?()=>_stepFrameBy(-1):null,icon:const Icon(Icons.chevron_left),color:Colors.white70,tooltip:'上一帧'),Expanded(child:Text(enabled?'${_safeFrameIndex+1} / $_frameCount':'请以 step 模式重新载入',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70,fontSize:12))),IconButton(onPressed:enabled&&_safeFrameIndex<_frameCount-1?()=>_stepFrameBy(1):null,icon:const Icon(Icons.chevron_right),color:Colors.white70,tooltip:'下一帧'),IconButton(onPressed:enabled&&_safeFrameIndex<_frameCount-1?_jumpToLatestFrame:null,icon:const Icon(Icons.last_page),color:Colors.white70,tooltip:'最新帧')]),const SizedBox(height:4),const Text('区间套箭头只读取当前 step frame；候选轨迹层只做UI观察，不参与计算。',style:TextStyle(color:Colors.white54,fontSize:11))]));}
 Widget _chartSettingsPanel()=>_panelBox('图层与指标设置',SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[const Text('指标默认隐藏，可在这里或 K 线图工具箱中打开。',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:10),Wrap(spacing:6,runSpacing:6,children:[for(final n in const <String>['MA','BOLL','VOL','MACD'])_indicatorChip(n)]),const SizedBox(height:12),SwitchListTile(value:_showBspCandidateTrail,onChanged:_loading?null:(v)=>setState(()=>_showBspCandidateTrail=v),dense:true,contentPadding:EdgeInsets.zero,title:const Text('未确认 BSP 候选轨迹层',style:TextStyle(color:Colors.white70,fontSize:12,fontWeight:FontWeight.w700)),subtitle:const Text('step 下保留曾出现后又撤销的 is_sure=false 点，标签带“候选轨迹?”。',style:TextStyle(color:Colors.white54,fontSize:11)))])));
 Widget _evidencePanel(){final a=_analysis;return _panelBox('复盘证据',a==null?const Center(child:Text('载入后可复制复盘证据。',style:TextStyle(color:Colors.white54))):SingleChildScrollView(child:SelectableText(_buildReplayEvidenceText(a),style:const TextStyle(color:Colors.white70,fontSize:11,height:1.35))));}
 Widget _chartPanel(ChanSnapshot? s){if(s==null||s.rawBars.isEmpty)return _panelBox('Chart',const Center(child:Text('Load replay to show chart.',style:TextStyle(color:Colors.white54))));return Stack(children:<Widget>[Positioned.fill(child:OriginKlineChart(snapshot:s,showFx:true,showFxLine:true,showFxText:true,showBi:true,showBiText:false,showSeg:true,showSegText:true,showZs:true,showBiBsp:true,showSegBsp:true,showMergedBars:false,showEasyTdxIndicators:_enabledEasyTdxIndicators.isNotEmpty,easyTdxSubPanelCount:2,enabledEasyTdxIndicators:_enabledEasyTdxIndicators,onEasyTdxIndicatorToggled:_toggleEasyTdxIndicator,drawingStorageKey:'s13_${_symbolController.text}_$_activeLevel',symbolLabel:'${_symbolController.text.trim()} $_activeLevel',windowSize:_windowSize,priceScale:_priceScale,viewEndIndex:_viewEndIndex,crosshairIndex:_crosshairIndex,onCrosshairChanged:(v)=>setState(()=>_crosshairIndex=v),onPanBars:_panChartByBars,onWindowSizeChanged:(v)=>setState(()=>_windowSize=v),onPriceScaleChanged:(v)=>setState(()=>_priceScale=v))),_intervalLinkOverlay()]);}
 Widget _intervalLinkOverlay(){final links=_visibleDownRelations;if(links.isEmpty)return const SizedBox.shrink();return Positioned(top:12,right:12,child:Material(color:Colors.transparent,child:Container(constraints:const BoxConstraints(maxWidth:320),padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:const Color(0xEE111722),borderRadius:BorderRadius.circular(12),border:Border.all(color:const Color(0x88FFD54F))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:<Widget>[Text(_isStepMode?'区间套链接 · 当前帧 $_stepFrameLabel':'区间套链接 · 最终快照',style:const TextStyle(color:Color(0xFFFFD54F),fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:6),for(final r in links)_intervalLinkButton(r)]))));}
 Widget _intervalLinkButton(LevelRelation r){final child=r.childLevel.trim().toUpperCase();return Padding(padding:const EdgeInsets.only(bottom:4),child:InkWell(borderRadius:BorderRadius.circular(8),onTap:()=>_jumpDownRelation(r),child:Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:Colors.white.withValues(alpha:0.06),borderRadius:BorderRadius.circular(8)),child:Row(mainAxisSize:MainAxisSize.min,children:<Widget>[const Icon(Icons.arrow_downward,size:14,color:Color(0xFFFFD54F)),const SizedBox(width:6),Flexible(child:Text('${r.parentLevel}@${r.parentRawIndex} → $child ${r.childStartRawIndex}-${r.childEndRawIndex}',overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w700)))])))));}
 Widget _levelChip(String l){final selected=_selectedLevels.contains(l);return FilterChip(label:Text(l),selected:selected,onSelected:_loading?null:(v)=>setState((){if(v){if(!_selectedLevels.contains(l))_selectedLevels.add(l);}else{_selectedLevels.remove(l);if(_activeLevel==l&&_selectedLevels.isNotEmpty)_activeLevel=_normalizedLevels.first;}_lastLevelValidation=_validateSelectedLevels().message;}),selectedColor:const Color(0xFFFFD54F),backgroundColor:const Color(0xFF20242E),labelStyle:TextStyle(color:selected?Colors.black:Colors.white70,fontSize:12));}
 Widget _activeLevelChip(String l){final selected=_activeLevel==l,canSelect=_currentSnapshot?.snapshots.containsKey(l)==true;return ChoiceChip(label:Text(l),selected:selected,onSelected:canSelect?(_)=>setState((){_activeLevel=l;_viewEndIndex=null;_crosshairIndex=null;_priceScale=1.0;}):null,selectedColor:const Color(0xFFFFD54F),backgroundColor:const Color(0xFF20242E),labelStyle:TextStyle(color:selected?Colors.black:Colors.white70,fontSize:12));}
 Widget _modeChip(String v){final selected=_mode==v;return ChoiceChip(label:Text(v),selected:selected,onSelected:_loading?null:(_)=>_setReplayMode(v),selectedColor:const Color(0xFFFFD54F),backgroundColor:const Color(0xFF20242E),labelStyle:TextStyle(color:selected?Colors.black:Colors.white70,fontSize:12));}
 Widget _indicatorChip(String n){final selected=_enabledEasyTdxIndicators.contains(n);return FilterChip(label:Text(n),selected:selected,onSelected:(_)=>_toggleEasyTdxIndicator(n),selectedColor:const Color(0xFFFFD54F),backgroundColor:const Color(0xFF20242E),labelStyle:TextStyle(color:selected?Colors.black:Colors.white70,fontSize:12));}
 void _toggleEasyTdxIndicator(String n){final k=n.trim().toUpperCase();if(k.isEmpty)return;setState((){if(_enabledEasyTdxIndicators.contains(k)){_enabledEasyTdxIndicators.remove(k);}else{_enabledEasyTdxIndicators.add(k);}});}void _panChartByBars(int bars){final s=_activeSnapshot;if(bars==0||s==null||s.rawBars.isEmpty)return;final max=s.rawBars.length-1,current=_viewEndIndex??max,next=(current+bars).clamp(0,max).toInt();if(next!=current)setState(()=>_viewEndIndex=next);}
 Widget _dropdownInt(String label,int value,List<int> options,ValueChanged<int> onChanged,{double width=96})=>SizedBox(width:width,child:DropdownButtonFormField<int>(value:value,dropdownColor:const Color(0xFF20242E),style:const TextStyle(color:Colors.white,fontSize:12),decoration:_decoration(label),items:[for(final o in options)DropdownMenuItem<int>(value:o,child:Text('$o'))],onChanged:_loading?null:(v){if(v!=null)onChanged(v);})) ;
 Widget _input(TextEditingController c,String label,{required double width,bool enabled=true})=>SizedBox(width:width,child:TextField(controller:c,enabled:enabled&&!_loading,style:const TextStyle(color:Colors.white,fontSize:12),decoration:_decoration(label)));
 Widget _panelBox(String title,Widget child)=>DecoratedBox(decoration:BoxDecoration(color:const Color(0xDD111722),borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.white.withValues(alpha:0.14))),child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700)),const SizedBox(height:8),Expanded(child:child)])));
 Widget _chip(String label,String value,bool ok){final color=ok?const Color(0xFF66BB6A):const Color(0xFFFFB74D);return Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:color.withValues(alpha:0.14),borderRadius:BorderRadius.circular(999),border:Border.all(color:color.withValues(alpha:0.45))),child:Text('$label: $value',style:TextStyle(color:color,fontSize:11,fontWeight:FontWeight.w700)));}
 InputDecoration _decoration(String label)=>InputDecoration(labelText:label,labelStyle:const TextStyle(color:Colors.white54,fontSize:11),isDense:true,filled:true,fillColor:const Color(0xFF1C2330),border:OutlineInputBorder(borderRadius:BorderRadius.circular(8)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(8),borderSide:const BorderSide(color:Colors.white24)),disabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(8),borderSide:const BorderSide(color:Colors.white12)));
 ButtonStyle _copyButtonStyle()=>OutlinedButton.styleFrom(foregroundColor:const Color(0xFF8AB4FF),side:const BorderSide(color:Color(0x668AB4FF)),padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),textStyle:const TextStyle(fontSize:11,fontWeight:FontWeight.w700));
 String _buildStatus(PythonMultiLevelChanAnalysis a,DateTime s,DateTime e){final m=a.meta;return 'S13 analyze_multi ${_mode.toUpperCase()} runtime_path:${_runtimePathText(a)} native:${m['native_cchan_lv_list']} fallback:${m['fallback_to_bridge']??false} frames:${a.frames.length} active_frame:$_stepFrameLabel levels:${a.snapshot.levels.join(',')} window:${_fmtDate(s)}~${_fmtDate(e)} links:${_visibleDownRelations.length} candidate_trail:$_bspCandidateTrailCount';}
 String _runtimePathText(PythonMultiLevelChanAnalysis a){final raw='${a.meta['runtime_path']??a.snapshot.meta['runtime_path']??RuntimePathController.current.wireName}'.trim();return raw=='slow_path'?'slow_path':'high_speed';}
 String _buildReplayEvidenceText(PythonMultiLevelChanAnalysis a)=><String>['s13_phase: single_stock_multilevel_replay_time_window_toolbar_interval_links_and_bsp_candidate_trail','symbol: ${_symbolController.text.trim()}','market: ${_marketController.text.trim().toUpperCase()}','selected_levels: ${_selectedLevels.join(',')}','normalized_levels: ${_normalizedLevels.join(',')}','level_validation: $_lastLevelValidation','active_level: $_activeLevel','runtime_path: ${_runtimePathText(a)}','replay_mode: $_mode','current_step: $_stepFrameLabel','request_window: $_effectiveWindowText','date_window_policy: start empty defaults to 1990-01-01; end empty defaults to system current time; count parameter removed','settings_layout: left_vertical_toolbar_with_stock_basic_settings_panel','chart_interval_link_policy: once uses final snapshot; step uses current frame only and validates parent/child rawIndex bounds','chart_interval_link_count: ${_visibleDownRelations.length}','bsp_candidate_trail_enabled: $_showBspCandidateTrail','bsp_candidate_trail_count: $_bspCandidateTrailCount','bsp_candidate_trail_policy: UI-only markers from past step frames; does not alter chan.py snapshot or calculation authority','enabled_easy_tdx_indicators: ${_enabledEasyTdxIndicators.isEmpty?'none':_enabledEasyTdxIndicators.join(',')}','source_policy: python/chan.py via native CChan(lv_list); Flutter/Dart display, route, request, and copy evidence only','backend_authority: native CChan(lv_list) through /api/chan/analyze_multi','native_cchan_lv_list: ${a.meta['native_cchan_lv_list']??a.snapshot.meta['native_cchan_lv_list']}','fallback_to_bridge: ${a.meta['fallback_to_bridge']??a.snapshot.meta['fallback_to_bridge']??false}','dart_chan_calculation_authority: false'].join('\n');
 Future<void> _copyText(String label,String text)async{await Clipboard.setData(ClipboardData(text:text));_showMessage('$label copied');}void _showMessage(String m){if(!mounted)return;ScaffoldMessenger.of(context).hideCurrentSnackBar();ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m),duration:const Duration(seconds:4)));}}
class _LevelValidationResult{final bool ok;final List<String> normalizedLevels;final String message;const _LevelValidationResult(this.ok,this.normalizedLevels,this.message);}
